Update README.md
Ackee-Blockchain/trdelnik pull request #59
Opened 2022-06-30 11:44 UTC by novakovadrea

Fixed grammar, added _Awards_ and _University and investment partners_ categories.

2022-06-30 11:49 UTC, tribuste commented on README.md
> +- [x] Q2/22 Trdelnik console, client and explorer introduced at Solana Hacker House Barcelona
Trdelnik console was not introduced yet.

2022-06-30 11:51 UTC, tribuste requested changes
It looks like you don't use Gitmoji, we can merge this one, but please for the next one use Gitmoji, you can find docs on Notion.

2022-07-11 11:29 UTC, stefanprokopdev approved these changes

2022-07-12 11:13 UTC, tribuste requested changes
Please squash the commits.

2022-07-12 11:31 UTC, stefanprokopdev commented
> Please squash the commits.

@tribuste maybe we can use this this time 
![image](https://user-images.githubusercontent.com/5623325/178480088-31ac7256-79c7-4535-9d76-f90453f433f4.png)

You can also update PR title - add gitmoji there and the squashed message should be generated from the title

2022-07-12 11:39 UTC, merged